name: 'Release'
on:
  push:
    branches:
      - 'release'
jobs:
  release:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'
      - name: 'Use Node.js 15.0'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '15.0'
      - name: 'Set up'
        run: |
          yarn install --frozen-lockfile
          yarn setup
      - name: 'Compile'
        run: 'yarn build'
      - name: 'Publish to NPM'
        run: 'yarn release'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
  push-to-main:
    needs:
      - 'release'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'
      - name: 'Use Node.js 15.0'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '15.0'
      - name: 'Set up'
        run: |
          yarn install --frozen-lockfile
          yarn setup
      - name: 'Compile'
        run: 'yarn build'
      - name: 'Push to Main'
        uses: 'ad-m/github-push-action@v0.6.0'
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: 'main'
          force: true
